# Generated by Django 5.1.3 on 2024-12-11 10:07

import datetime
import django.utils.timezone
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=20)),
                ('add', models.TextField(default='enter your address')),
                ('email', models.EmailField(default='enter your email address', max_length=254)),
                ('number', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=8)),
                ('cpass', models.CharField(max_length=8)),
                ('date_and_time', models.DateTimeField(default=datetime.datetime(2024, 12, 11, 15, 37, 1, 140062))),
                ('dob', models.DateField(default=django.utils.timezone.get_current_timezone)),
                ('flottie', models.FloatField(default=12)),
                ('raju', models.DecimalField(decimal_places=2, max_digits=5)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('gender', models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female'), ('o', 'others')], max_length=1)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
